### ISSUE TITLE
issue with Relay method

### ISSUE THREAD

**Issue by macsimc** [TheSuunny/Yove.Proxy#1]
I used your library for a small project and it wasn't quite working.
The issue was there:
`  private void Relay(Socket Source, Socket Target)
        {
            try
            {
                Task.Run(() => { Relay(Target, Source); });`
This will start quite a few threads until one of the sockets dies. The task needs to run only once

**Comment by TheSuunny** [comment]
Thank you very much for informing me about this problem, I'm sorry for my long absence, the project has been completely updated. 39e8fd49c40845652d0775d506c9d39e138ebc35
