### ISSUE TITLE
System.Net.Sockets.SocketException: Address already in use

### ISSUE THREAD

**Issue by Arcanaeum** [TheSuunny/Yove.Proxy#2]
Hello,

I am trying to create a large number of proxies of both Socks4 and Socks5 type. When I do so, I get this error:

```
Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Yove.Proxy.ProxyClient.CreateInternalServer()
   at Yove.Proxy.ProxyClient..ctor(String Host, Int32 Port, ProxyType Type)
```

Any ideas how I can resolve this?

**Comment by TheSuunny** [comment]
Hello, I assume you're using .net core and Linux?

**Comment by TheSuunny** [comment]
I updated project, try to add the project, if you are on .Net core, then through the terminal - 
```
dotnet add reference Yove.Proxy.csproj
```

**Comment by Arcanaeum** [comment]
Thanks! This solves this particular problem. You are correct that I am using .net core and Linux (should have mentioned that, sorry).

The issue now is that every proxy created leaves a socket open in the LISTENING state. So if I have a few thousand proxies I very quickly run out of available sockets. For example, after a few thousand requests:
```
arc@vmi266472:~$ netstat -nat | awk '{print $6}' | sort | uniq -c | sort -n
      1 established)
      1 Foreign
     13 ESTABLISHED
     41 TIME_WAIT
  23093 LISTEN
```

Here is how I make my requests:
```
            var handler = new HttpClientHandler {
                Proxy = proxy?.TheProxy         // TheProxy is a IWebProxy which is either a Yove Proxy or a normal WebProxy       
            };

            try
            {
                using (var cts = new CancellationTokenSource())
                using (var client = new HttpClient(handler))
                {                
                    var request = new HttpRequestMessage(HttpMethod.Get, url);

                    cts.CancelAfter(TimeSpan.FromSeconds(10));

                    using (var response = await client.SendAsync(request, cts.Token))
                    {
                        return await response.Content.ReadAsStringAsync();
                    }
                }
            }
            catch
            {
                return "";
            }
```

I haven't tried without the cancellation token yet - going to try that in a minute - but I don't think that's the cause. Do you have any suggestions?

(I know you're supposed to reuse HttpClients, but creating a new one each time hasn't caused an issue until I tried to implement Socks4/5)

Edit: To confirm, this simpler code displays the same behaviour:
```
        public static string Get8(string url, Proxy proxy = null)
        {
            try
            {
                using (var handler = new HttpClientHandler())
                {
                    handler.Proxy = proxy?.TheProxy; // An IWebProxy
                    using (var client = new HttpClient(handler))
                    {
                        client.Timeout = TimeSpan.FromSeconds(5);

                        return client.GetStringAsync(url).Result;
                    }
                }
            }
            catch
            {
                return "";
            }
        }
```

Edit 2: Looking at the code for the ProxyClient, it seems that the issue is that a new internal server is created for each proxyclient object I create. Is there any way to reuse a proxyclient and change the host and port?

**Comment by nexepu** [comment]
Hello, i have the same issue of running out of ports, i can confirm this bug in windows too.

**Comment by TheSuunny** [comment]
@pyrocept Try to put the project directly, I have not yet updated the package in Nuget.

**Comment by TheSuunny** [comment]
@Arcanaeum I'm already working on it.

**Comment by TheSuunny** [comment]
@Arcanaeum @pyrocept I have sent 1.0.3 version to Nuget, please try it.

**Comment by Arcanaeum** [comment]
Okay - we are making progress! No more infinite `LISTENING` sockets. Hooray!

However, now we have a new issue. When you try to create a request through a proxy client there are (at least) four possibilities:

1. The proxy accepts the request, and responds with the response
2. The proxy accepts the request, but doesn't respond with a response
3. The proxy refuses the request
4. The proxy can't even be reached.

Sometimes when 4. occurs, I get this exception:
```
Unhandled Exception: System.Exception: Could not connect to proxy server - ConnectionRefused
   at Yove.Proxy.ProxyClient.AcceptCallback(IAsyncResult e) in /home/arc/ProxyMagic/Yove.Proxy/ProxyClient.cs:line 159
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
There is no way to catch this exception - it crashes the program regardless.
That's more of a minor annoyance though. The bigger issue is in case 2&3. When I make a large number of requests to a large number of proxies, this is what happens at a system level:

```
arc@vmi266472:~$ netstat -nat | awk '{print $6}' | sort | uniq -c | sort -n
      1 established)
      1 Foreign
      3 LAST_ACK
      3 SYN_RECV
     12 TIME_WAIT
     25 FIN_WAIT2
    176 SYN_SENT
   1128 CLOSE_WAIT
   1648 LISTEN
   3216 ESTABLISHED
```
Notice the insane number of `ESTABLISHED`, and `CLOSE_WAIT` and still high number of `LISTENING`. 
`ESTABLISHED` means there is an open connection - and this persists forever until I terminate the program. Even if I use a timeout/async `CancellationToken`.
`CLOSE_WAIT` means the kernel is waiting for the program to close the socket. Not sure why this is the case (I have tried calling dispose on the `ProxyClient`s and putting them in a `using` block).
And of course we know what `LISTENING` is. Again, the listening seems to persist long after the timeout should have stopped it from listening. But maybe that's just a symptom of the system getting hung up on so many established/close_wait sockets - who knows.

Sorry for so many issues!

**Comment by TheSuunny** [comment]
@Arcanaeum On the contrary, thank You, because I do not use this project for their own purposes, and is currently developing only for users who are interested in it, I have already taken up this work :)

**Comment by TheSuunny** [comment]
@Arcanaeum Please try again, i will not send to Nuget, if you are OK, then i will send.

**Comment by Arcanaeum** [comment]
My apologies, I have been away a few days. I will try again and let you know!
