### ISSUE TITLE
Proxy Authentification

### ISSUE THREAD

**Issue by ghost** [TheSuunny/Yove.Proxy#3]
Hello budd, i love your work and if you could please add proxy authentification with username and password thanks c:

**Comment by TheSuunny** [comment]
> Hello budd, i love your work and if you could please add proxy authentification with username and password thanks c:

Hi, yes, of course, but could you provide me with a test proxy? So that I can check the performance of authorization

**Comment by TheSuunny** [comment]
> > Hello budd, i love your work and if you could please add proxy authentification with username and password thanks c:
> 
> Hi, yes, of course, but could you provide me with a test proxy? So that I can check the performance of authorization

Or can I post a commit to a branch here, and after you check, I will send it to Nuget, how it is convenient for you?

**Comment by TheSuunny** [comment]
I checked with myself and uploaded the new version to both the branch and Nuget, please check with and let me know about the result.

https://www.nuget.org/packages/Yove.Proxy

**Comment by ghost** [comment]
Okay thanks c:

**Comment by ghost** [comment]
Thanks you dude, it's working flawlessly.
Have a greatful day !

**Comment by TheSuunny** [comment]
Okay, thank you too :)
